spring:
  application:
    name: expense-tracker

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL:jdbc:mysql://localhost:3307/expense_tracker_db}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

api:
  base: /api
  version: /v1

cloudinary:
  secret:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}




app:
  queue:
    otp: otpQueue
    forgot-password: forgotPasswordQueue
    reset-password: resetPasswordQueue
    change-password: changePasswordQueue
    account-created: accountCreatedQueue
    profile-event: profileEventQueue
  frontend:
    path: http://localhost:3001

  logo: https://i.imghippo.com/files/SuCD1097ccM.png

  cors:
    allowed-origins: "http://localhost:3000, http://localhost:3001, http://localhost:3002, http://localhost:3003, http://localhose:3004"